# DO NOT CHANGE the "init" and "install" sections below
image: Windows Server 2019

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: true
    # env vars that may need to be set, at least temporarily, from time to time
    # see https://github.com/krlmlr/r-appveyor#readme for details
    USE_RTOOLS: true
    R_REMOTES_STANDALONE: true
  matrix:
    - R_VERSION: stable
    - R_VERSION: patched
    - R_VERSION: devel

build_script:
  - travis-tool.sh install_github ropensci/outsider.base
  - travis-tool.sh install_github ropensci/outsider
  - travis-tool.sh install_deps
  - ps: Write-host "`n*** VM CONFIGURATION ***`n" -foregroundcolor yellow
  - ps: Write-host "`nCheck number of logical CPUs" -foregroundcolor green
  - ps: gcim Win32_Processor | % { "$($_.NumberOfLogicalProcessors) logical CPUs" }
  - ps: Write-host "`nCheck memory size" -foregroundcolor green
  - ps: gcim Win32_OperatingSystem | % { "$([int]($_.TotalVisibleMemorySize/1mb)) Gb" }
  - ps: Write-host "`n*** DOCKER ***`n" -foregroundcolor yellow
  - ps: Write-host "`nSwitch to linux engine"  -foregroundcolor green
  - docker-switch-linux
  - ps: Write-host "`nList local docker linux images"  -foregroundcolor green
  - docker images
  - docker run --rm busybox echo hello_world_busybox

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
